### ISSUE TITLE
Stream outputs don't show backspace characters sometimes

### ISSUE THREAD

**Issue by captainsafia** [nteract/ansi-to-react#36]
Migrating this from an external bug tracker.

I am not sure if it is our bug or not.
Try running "!conda install nltk -y", you can see that some of the output looks like this: "Solving environment: / - \ | / - \ | / - \ | /", where block character stands backspace, I assume, and it is supposed to erase previous state of the spinner.

On the other hand, later when you see progress bars growing such as this:
Downloading and Extracting Packages conda-4.7.11 | 3.0 MB | ##################################### | 100% 
I think in that case backspace is being handled correctly, because you can see numbers appearing first, then they are getting erased, and then "#" appears.

So this is why I am hesitant to call that we do not handle backspaces - it looks like in some cases we do, but in others, such as with this spinner, we don't.

In either case, I think we should fix these spinners.

**Comment by williamstein** [comment]
I've been working on a [related issue](https://github.com/sagemathinc/cocalc/issues/2520) in CoCalc today, and the solution for us is "use ansi-to-react more".   

> So this is why I am hesitant to call that we do not handle backspaces - it looks like in some cases we do, but in others, such as with this spinner, we don't.

ansi-to-react handles `\r` properly (evidently \r means "move to beginning of line"), but it does NOT handle `\b` (backspace) at all.  Classical official Jupyter notebook handles `\r` the same way as ansi-to-react, but Jupyter also handles `\b`, but in way that is inconsistent with the Python command line.   There's a couple of tickets and stackoverflows related to this; Jason Grout and I put some links here:
https://github.com/sagemathinc/cocalc/issues/2520[](url)

*Fortunately* the progress bar libraries I know of for Python use `\r` and not `\b`, so ansi-to-react perhaps sufficient having only implement `\r` support.   There's an example at the link above.

It would be nice if ansi-to-react also implements `\b` support, since then cocalc and nteract wouldn't do this sort of thing:

![image](https://user-images.githubusercontent.com/1276278/82272619-f5870280-992f-11ea-901a-3f9118308fe0.png)

though I don't know of any cases in the wild where this matters.  Note that if you implement `\b` you'll have to decide between making it work like Jupyter classic / JupyterLab, or making it work like the Python command line terminal, which are different in the case of multiple \b's:

![image](https://user-images.githubusercontent.com/1276278/82272698-31ba6300-9930-11ea-9c88-41299506503f.png)



@jasongrout

**Comment by captainsafia** [comment]
> I've been working on a related issue in CoCalc today, and the solution for us is "use ansi-to-react more".

Glad to hear that the package was helpful for you here!

> Note that if you implement \b you'll have to decide between making it work like Jupyter classic / JupyterLab, or making it work like the Python command line terminal, which are different in the case of multiple \b's:

I'm inclined to make it work like Classic. That tends to be the point of reference for most users and is, indeed, the point of reference for this original issue as well.

Thanks for writing this issue. It cuts a lot of the research work from the resolution for this.

I noticed in the other issue that you mentioned rendering some outputs using xterm.js. I mused through this idea as well when originally thinking about this problem. It makes sense to render a lot of cell outputs for executions of bash commands through an xterm like UI.

**Comment by williamstein** [comment]
>  It makes sense to render a lot of cell outputs for executions of bash commands through an xterm like UI.

That definitely makes sense.  I don't think it would be too hard, since xterm.js is a very nice usable library at this point.

**Comment by williamstein** [comment]
Hi @captainsafia and maybe @rgbkrk .  We're getting more complaints about this "\b is not implemented" issue from users, e.g., which is why I opened https://github.com/sagemathinc/cocalc/issues/5044 today.  Of course nteract has the same bug, so maybe one of you wants to implement \b support sometime soon, since the repo has had no releases since 2017...      I might find time to look into this as well.

If I do, I agree with Safia -- make it work like classic.  I don't really care at all which way it works (when arbitrary choices come up), but classic is indeed a solid point of reference when there is no compelling argument either way.

**Comment by williamstein** [comment]
I fixed this.  I was a little surprised that I was just able to push to master.  I didn't expect that.  Sorry if this causes any trouble.  In any case, I just pushed a commit that handles \b in the exact same way as Jupyter classic, added tests, and documentation.  It's ugly and arguably buggy, but users will probably be happier...
